## Парсим офисы с Авито

In [1]:
import time
import pickle
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import requests
r = requests.get('http://icanhazip.com/')
r.content
# returns my regular IP

b'213.87.132.32\n'

In [3]:
import numpy as np 
import pandas as pd
from tqdm import tqdm_notebook # Красивые циклы
from bs4 import BeautifulSoup
from user_agent import generate_user_agent

In [ ]:
# Анонимизация 
# В консоли: pip install PySocks
import socks
import socket
socks.set_default_proxy(socks.SOCKS5, "localhost", 9150)
socket.socket = socks.socksocket
# ТОР по умолчанию идет через сокет 9150

from urllib.request import urlopen
print(urlopen('http://icanhazip.com').read())

# Для того, чтобы изменить частоту смены ip находим в папке, где стоит TOR
# файл torcc и в него добавляем строки: 

# HiddenServiceStatistics 0
# CircuitBuildTimeout 10
# LearnCircuitBuildTimeout 0
# MaxCircuitDirtiness 10

In [ ]:
#  Просто смотрим раз в сколько минут меняется ip. По дефолту раз в 10 минут 
for i in range(10):
    print(urlopen('http://icanhazip.com').read())
    time.sleep(30)

Делаем ссылки

In [ ]:
text = '<div class="catalog-counts__more" style=""><ul><li><a class="js-catalog-counts__link" href="/moskva/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Москва</a><span class="c-2 catalog-counts__number"> 10 886</span></li><li><a class="js-catalog-counts__link" href="/moskovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Московская обл.</a><span class="c-2 catalog-counts__number"> 2 677</span></li><li><a class="js-catalog-counts__link" href="/sankt-peterburg/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Санкт-Петербург</a><span class="c-2 catalog-counts__number"> 5 329</span></li><li><a class="js-catalog-counts__link" href="/leningradskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ленинградская обл.</a><span class="c-2 catalog-counts__number"> 175</span></li><li><a class="js-catalog-counts__link" href="/adygeya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Адыгея</a><span class="c-2 catalog-counts__number"> 46</span></li><li><a class="js-catalog-counts__link" href="/altayskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Алтайский край</a><span class="c-2 catalog-counts__number"> 419</span></li><li><a class="js-catalog-counts__link" href="/amurskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Амурская обл.</a><span class="c-2 catalog-counts__number"> 119</span></li><li><a class="js-catalog-counts__link" href="/arhangelskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Архангельская обл.</a><span class="c-2 catalog-counts__number"> 123</span></li><li><a class="js-catalog-counts__link" href="/astrahanskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Астраханская обл.</a><span class="c-2 catalog-counts__number"> 190</span></li><li><a class="js-catalog-counts__link" href="/bashkortostan/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Башкортостан</a><span class="c-2 catalog-counts__number"> 1 492</span></li><li><a class="js-catalog-counts__link" href="/belgorodskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Белгородская обл.</a><span class="c-2 catalog-counts__number"> 266</span></li><li><a class="js-catalog-counts__link" href="/bryanskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Брянская обл.</a><span class="c-2 catalog-counts__number"> 163</span></li><li><a class="js-catalog-counts__link" href="/buryatiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Бурятия</a><span class="c-2 catalog-counts__number"> 87</span></li><li><a class="js-catalog-counts__link" href="/vladimirskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Владимирская обл.</a><span class="c-2 catalog-counts__number"> 421</span></li><li><a class="js-catalog-counts__link" href="/volgogradskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Волгоградская обл.</a><span class="c-2 catalog-counts__number"> 643</span></li><li><a class="js-catalog-counts__link" href="/vologodskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Вологодская обл.</a><span class="c-2 catalog-counts__number"> 221</span></li><li><a class="js-catalog-counts__link" href="/voronezhskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Воронежская обл.</a><span class="c-2 catalog-counts__number"> 536</span></li><li><a class="js-catalog-counts__link" href="/dagestan/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Дагестан</a><span class="c-2 catalog-counts__number"> 91</span></li><li><a class="js-catalog-counts__link" href="/evreyskaya_ao/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Еврейская АО</a><span class="c-2 catalog-counts__number"> 15</span></li><li><a class="js-catalog-counts__link" href="/zabaykalskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Забайкальский край</a><span class="c-2 catalog-counts__number"> 117</span></li><li><a class="js-catalog-counts__link" href="/ivanovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ивановская обл.</a><span class="c-2 catalog-counts__number"> 217</span></li></ul><ul><li><a class="js-catalog-counts__link" href="/ingushetiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ингушетия</a><span class="c-2 catalog-counts__number"> 1</span></li><li><a class="js-catalog-counts__link" href="/irkutskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Иркутская обл.</a><span class="c-2 catalog-counts__number"> 568</span></li><li><a class="js-catalog-counts__link" href="/kabardino-balkariya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Кабардино-Балкария</a><span class="c-2 catalog-counts__number"> 41</span></li><li><a class="js-catalog-counts__link" href="/kaliningradskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Калининградская обл.</a><span class="c-2 catalog-counts__number"> 355</span></li><li><a class="js-catalog-counts__link" href="/kalmykiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Калмыкия</a><span class="c-2 catalog-counts__number"> 20</span></li><li><a class="js-catalog-counts__link" href="/kaluzhskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Калужская обл.</a><span class="c-2 catalog-counts__number"> 202</span></li><li><a class="js-catalog-counts__link" href="/kamchatskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Камчатский край</a><span class="c-2 catalog-counts__number"> 28</span></li><li><a class="js-catalog-counts__link" href="/karachaevo-cherkesiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Карачаево-Черкесия</a><span class="c-2 catalog-counts__number"> 27</span></li><li><a class="js-catalog-counts__link" href="/kareliya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Карелия</a><span class="c-2 catalog-counts__number"> 187</span></li><li><a class="js-catalog-counts__link" href="/kemerovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Кемеровская обл.</a><span class="c-2 catalog-counts__number"> 419</span></li><li><a class="js-catalog-counts__link" href="/kirovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Кировская обл.</a><span class="c-2 catalog-counts__number"> 253</span></li><li><a class="js-catalog-counts__link" href="/komi/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Коми</a><span class="c-2 catalog-counts__number"> 134</span></li><li><a class="js-catalog-counts__link" href="/kostromskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Костромская обл.</a><span class="c-2 catalog-counts__number"> 133</span></li><li><a class="js-catalog-counts__link" href="/krasnodarskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Краснодарский край</a><span class="c-2 catalog-counts__number"> 2 360</span></li><li><a class="js-catalog-counts__link" href="/krasnoyarskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Красноярский край</a><span class="c-2 catalog-counts__number"> 521</span></li><li><a class="js-catalog-counts__link" href="/respublika_krym/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Крым</a><span class="c-2 catalog-counts__number"> 673</span></li><li><a class="js-catalog-counts__link" href="/kurganskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Курганская обл.</a><span class="c-2 catalog-counts__number"> 195</span></li><li><a class="js-catalog-counts__link" href="/kurskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Курская обл.</a><span class="c-2 catalog-counts__number"> 131</span></li><li><a class="js-catalog-counts__link" href="/lipetskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Липецкая обл.</a><span class="c-2 catalog-counts__number"> 210</span></li><li><a class="js-catalog-counts__link" href="/magadanskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Магаданская обл.</a><span class="c-2 catalog-counts__number"> 20</span></li><li><a class="js-catalog-counts__link" href="/mariy_el/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Марий Эл</a><span class="c-2 catalog-counts__number"> 65</span></li></ul><ul><li><a class="js-catalog-counts__link" href="/mordoviya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Мордовия</a><span class="c-2 catalog-counts__number"> 105</span></li><li><a class="js-catalog-counts__link" href="/murmanskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Мурманская обл.</a><span class="c-2 catalog-counts__number"> 154</span></li><li><a class="js-catalog-counts__link" href="/nenetskiy_ao/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ненецкий АО</a><span class="c-2 catalog-counts__number"> 2</span></li><li><a class="js-catalog-counts__link" href="/nizhegorodskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Нижегородская обл.</a><span class="c-2 catalog-counts__number"> 940</span></li><li><a class="js-catalog-counts__link" href="/novgorodskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Новгородская обл.</a><span class="c-2 catalog-counts__number"> 139</span></li><li><a class="js-catalog-counts__link" href="/novosibirskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Новосибирская обл.</a><span class="c-2 catalog-counts__number"> 626</span></li><li><a class="js-catalog-counts__link" href="/omskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Омская обл.</a><span class="c-2 catalog-counts__number"> 255</span></li><li><a class="js-catalog-counts__link" href="/orenburgskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Оренбургская обл.</a><span class="c-2 catalog-counts__number"> 275</span></li><li><a class="js-catalog-counts__link" href="/orlovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Орловская обл.</a><span class="c-2 catalog-counts__number"> 108</span></li><li><a class="js-catalog-counts__link" href="/penzenskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Пензенская обл.</a><span class="c-2 catalog-counts__number"> 210</span></li><li><a class="js-catalog-counts__link" href="/permskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Пермский край</a><span class="c-2 catalog-counts__number"> 997</span></li><li><a class="js-catalog-counts__link" href="/primorskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Приморский край</a><span class="c-2 catalog-counts__number"> 26</span></li><li><a class="js-catalog-counts__link" href="/pskovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Псковская обл.</a><span class="c-2 catalog-counts__number"> 78</span></li><li><a class="js-catalog-counts__link" href="/respublika_altay/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Республика Алтай</a><span class="c-2 catalog-counts__number"> 16</span></li><li><a class="js-catalog-counts__link" href="/rostovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ростовская обл.</a><span class="c-2 catalog-counts__number"> 1 587</span></li><li><a class="js-catalog-counts__link" href="/ryazanskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Рязанская обл.</a><span class="c-2 catalog-counts__number"> 262</span></li><li><a class="js-catalog-counts__link" href="/samarskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Самарская обл.</a><span class="c-2 catalog-counts__number"> 1 520</span></li><li><a class="js-catalog-counts__link" href="/saratovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Саратовская обл.</a><span class="c-2 catalog-counts__number"> 465</span></li><li><a class="js-catalog-counts__link" href="/sahalinskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Сахалинская обл.</a><span class="c-2 catalog-counts__number"> 7</span></li><li><a class="js-catalog-counts__link" href="/saha_yakutiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Саха (Якутия)</a><span class="c-2 catalog-counts__number"> 26</span></li><li><a class="js-catalog-counts__link" href="/sverdlovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Свердловская обл.</a><span class="c-2 catalog-counts__number"> 1 102</span></li></ul><ul><li><a class="js-catalog-counts__link" href="/severnaya_osetiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Северная Осетия</a><span class="c-2 catalog-counts__number"> 60</span></li><li><a class="js-catalog-counts__link" href="/smolenskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Смоленская обл.</a><span class="c-2 catalog-counts__number"> 227</span></li><li><a class="js-catalog-counts__link" href="/stavropolskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ставропольский край</a><span class="c-2 catalog-counts__number"> 537</span></li><li><a class="js-catalog-counts__link" href="/tambovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Тамбовская обл.</a><span class="c-2 catalog-counts__number"> 96</span></li><li><a class="js-catalog-counts__link" href="/tatarstan/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Татарстан</a><span class="c-2 catalog-counts__number"> 1 634</span></li><li><a class="js-catalog-counts__link" href="/tverskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Тверская обл.</a><span class="c-2 catalog-counts__number"> 343</span></li><li><a class="js-catalog-counts__link" href="/tomskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Томская обл.</a><span class="c-2 catalog-counts__number"> 175</span></li><li><a class="js-catalog-counts__link" href="/tulskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Тульская обл.</a><span class="c-2 catalog-counts__number"> 335</span></li><li><a class="js-catalog-counts__link" href="/tyva/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Тыва</a><span class="c-2 catalog-counts__number"> 10</span></li><li><a class="js-catalog-counts__link" href="/tyumenskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Тюменская обл.</a><span class="c-2 catalog-counts__number"> 352</span></li><li><a class="js-catalog-counts__link" href="/udmurtiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Удмуртия</a><span class="c-2 catalog-counts__number"> 438</span></li><li><a class="js-catalog-counts__link" href="/ulyanovskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ульяновская обл.</a><span class="c-2 catalog-counts__number"> 310</span></li><li><a class="js-catalog-counts__link" href="/habarovskiy_kray/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Хабаровский край</a><span class="c-2 catalog-counts__number"> 346</span></li><li><a class="js-catalog-counts__link" href="/hakasiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Хакасия</a><span class="c-2 catalog-counts__number"> 91</span></li><li><a class="js-catalog-counts__link" href="/hanty-mansiyskiy_ao/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ханты-Мансийский АО</a><span class="c-2 catalog-counts__number"> 297</span></li><li><a class="js-catalog-counts__link" href="/chelyabinskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Челябинская обл.</a><span class="c-2 catalog-counts__number"> 947</span></li><li><a class="js-catalog-counts__link" href="/chechenskaya_respublika/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Чеченская Республика</a><span class="c-2 catalog-counts__number"> 21</span></li><li><a class="js-catalog-counts__link" href="/chuvashiya/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Чувашия</a><span class="c-2 catalog-counts__number"> 167</span></li><li><a class="js-catalog-counts__link" href="/yamalo-nenetskiy_ao/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ямало-Ненецкий АО</a><span class="c-2 catalog-counts__number"> 92</span></li><li><a class="js-catalog-counts__link" href="/yaroslavskaya_oblast/kommercheskaya_nedvizhimost?s=101&amp;view=list&amp;q=%D0%BE%D1%84%D0%B8%D1%81">Ярославская обл.</a><span class="c-2 catalog-counts__number"> 376</span></li></ul></div>'
txt = text.split('href="')[1:]
txt1 = [item.split('</a>')[0] for item in txt]
city_urls = { }
for item in txt1:
    cur = item.split('">')
    city_urls[cur[1]] = cur[0]

In [ ]:
def href_maker(url):
    page_1 = 'https://www.avito.ru'+ url.split('?')[0] + '/sdam/v_mesyats/ofis?p='
    x = url.split('?')[1].split('&amp')
    page_2 = '&' +  x[0] + '&' + x[1][1:]
    return page_1, page_2

In [ ]:
page_1, page_2 = href_maker(city_urls['Москва'])
main_page = page_1 + str(3) + page_2
main_page

In [ ]:
len(city_urls)

## Пробуем скачат всё

In [ ]:
%%time 
all_data = { }
bag_infa = { }

for key in city_urls.keys():
    print('Сейчас я попробую скачать объявления по ', key)
    print('Текущий ip ', urlopen('http://icanhazip.com').read())
    page_1, page_2 = href_maker(city_urls[key])
    # Временные векторы для данных 
    titles = [ ]
    hrefs = [ ]
    city = [ ]
    price = [ ]
    bagi = [ ]
    # Буду стараться скачать 100 страниц с объявлениями по данному городу. 
    for i in range(1,101):
        try:
            main_page = page_1 + str(i) + page_2
            response = requests.get(main_page,headers = {'User-Agent':generate_user_agent()})
            html = response.content
            soup = BeautifulSoup(html,'html.parser')

            off = soup.find_all('a',{'class':"description-title-link"})
            titles.extend([a.attrs['title'] for a in off])
            hrefs.extend([a.attrs['href'] for a in off])

            ct = soup.find_all('p',{'class':"data-chunk"})
            city.extend([item.text for item in ct])
            price.extend(soup.find_all('div', {'class' : 'price'}))
        except:
            bagi.append(i)
    all_data[key] = [titles, hrefs, city, price]
    bag_infa [key] = [[len(price),len(city),len(titles),len(hrefs)],bagi] 
    print(len(price),len(city),len(titles),len(hrefs),'\n')

In [ ]:
new_all_data = { }
for key in all_data.keys():
    s = all_data[key]
    new_all_data[key] = [s[0],s[1],s[2],[item.text for item in s[3]],s[4]]

In [ ]:
with open('avito_off', 'wb') as f:
    pickle.dump(new_all_data, f)

In [ ]:
with open('avito_bagi', 'wb') as f:
    pickle.dump(bag_infa, f)

## Обработочка данных

In [4]:
with open('avito_off', 'rb') as f:
     new_all_data = pickle.load(f)

In [5]:
ft0 = [ ]
ft1 = [ ]
ft2 = [ ]
ft3 = [ ]
ft4 = [ ]
for key in new_all_data.keys():
    s = new_all_data[key]
    ft0.extend(s[0])
    ft1.extend(s[1])
    ft3.extend(s[3])
    ft4.extend(s[4])
    if len(s[2]) == 0:
        ft2.extend([key]*len(s[0]))
    else:
        ft2.extend(s[2])
print(len(ft0),len(ft1),len(ft2),len(ft3),len(ft4))

29073 29073 29073 29073 29073

In [6]:
avito_df = pd.DataFrame( ) 
avito_df['office'] = ft0 
avito_df['href'] = ft1
avito_df['city'] = ft2 
avito_df['dirty_price'] = ft3 
avito_df['subject'] = ft4
# Скопируем таблицу для сбора инфы по сайту 
dirty_avito_df = avito_df.copy()

avito_df.head()

,office,href,city,dirty_price,subject
0,"Офисное помещение, 66 м² в Уссурийске",/ussuriysk/kommercheskaya_nedvizhimost/ofisnoe...,Уссурийск,\n 46 200 р. в месяц \n\n,Приморский край
1,Офис 81 м² в Владивостоке,/vladivostok/kommercheskaya_nedvizhimost/ofis_...,Владивосток,\n 40 000 р. в месяц \n\n,Приморский край
2,"Офис в центре города, 30.2 м² в Находке",/nahodka/kommercheskaya_nedvizhimost/ofis_v_ts...,Находка,\n 22 650 р. в месяц \n\n,Приморский край
3,"Офис в здании гостиницы Рент, 41.1 м² в Находке",/nahodka/kommercheskaya_nedvizhimost/ofis_v_zd...,Находка,\n 29 990 р. в месяц \n\n,Приморский край
4,"Офис, 22.7 м² в Находке",/nahodka/kommercheskaya_nedvizhimost/ofis_22.7...,Находка,\n 17 025 р. в месяц \n\n,Приморский край

## Попробуем по каждому объявлению собрать дополнительную инфу и избежать бана

In [7]:
href_list = list(dirty_avito_df.href)
print(len(href_list))
href_list = list(set(href_list))
print(len(href_list))

29073
28895

In [10]:
# Кусок кода на случай, если всё накрывается
hr_copy = href_list.copy()
    
with open('avito_data3', 'rb') as f:
    adding_inf = pickle.load(f)
    
seen_hrefs = [item[0] for item in adding_inf]

for item in seen_hrefs:
    hr_copy.remove(item)

print(len(hr_copy))
print(len(adding_inf))

3392
25503

In [ ]:
%%time
# Закоменчено, так как всё накрывалось несколько раз 
# adding_inf = [ ]
# hr_copy = href_list.copy()
save_j = 2

while len(hr_copy) > 0:
    print('\n', 'На данной итерации: ', len(hr_copy))
    seen_hrefs = [ ]
    for hr in tqdm_notebook(hr_copy):
        try:
            url = 'https://www.avito.ru' + hr
            response = requests.get(url)
            html = response.content
            soup = BeautifulSoup(html,'html.parser')

            x1 = soup.find_all('div',{'class':"item-params"})[0].text.strip()
            x2 = soup.find_all('span',{'class':"price-value-string js-price-value-string"})[0].text.strip()
            adding_inf.append([hr,x1,x2])
            seen_hrefs.append(hr)
        except:
            print('Забанено')
            continue
            
    # На всякий случай сохраним накаченое за итерацию 
    with open('avito_data' + str(save_j), 'wb') as f:
        pickle.dump(data, f)
    save_j += 1    
    
    for item in seen_hrefs:
        hr_copy.remove(item)

In [ ]:
# Сохраняем 
with open('avito_data' + str(3), 'wb') as f:
    pickle.dump(adding_inf, f)
    
# Если всё накрылось, запускаем строчки ниже, чтобы выбросить все уже 
# просмотренные ссылки

In [ ]:
len(hr_copy)

In [ ]:
len(seen_hrefs)

In [ ]:
for item in seen_hrefs:
    hr_copy.remove(item)

In [ ]:
len(hr_copy)

In [ ]:
len(adding_inf)

In [ ]:
adding_inf[-1]

## Объединяе и запиливаем табличку

In [11]:
add_df = pd.DataFrame(adding_inf)
add_df.columns = ['href','Площадь11','Цена11']

In [22]:
print(len(set(add_df['href'])))

25503

In [21]:
full_df = pd.merge(add_df,avito_df.drop_duplicates(['href']),on='href',how='left')
print(add_df.shape)
print(avito_df.shape)
print(full_df.shape)

(25503, 3)
(29073, 5)
(25503, 7)

In [25]:
full_df.head(2)

,href,Площадь11,Цена11,office,city,dirty_price,subject
0,/podolsk/kommercheskaya_nedvizhimost/mini-ofis...,Площадь: 19.5 м²; \nКласс здания: a,13 615 ₽ в месяц,"Мини-офис (№111) 19,45 м² в Подольске",Подольск,\n 13 615 р. в месяц \n\n,Московская обл.
1,/moskva/kommercheskaya_nedvizhimost/sdam_ofisn...,Площадь: 2700 м²,10 000 ₽ в год за м²,"Сдам офисное помещение, 2700 м² в Москве",Москва,\n 2 250 000 р. в месяц \n\n,Москва

## Чистка таблицы

In [27]:
avito_df = full_df.copy()

In [28]:
avito_df['freq'] =\
      [re.sub('[^а-яА-Я]','',item.split('р.')[-1]) for item in avito_df['dirty_price']]

avito_df['clean_price'] =\
      [re.sub('[^0-9]','',item.split('р.')[0]) for item in avito_df['dirty_price']]

avito_df['clean_price'].replace({'':np.nan}, inplace = True)
avito_df['clean_price'] = avito_df['clean_price'].astype(float)

avito_df['dirty_qv'] = [re.findall(r'\w+ м²|\w+м²',obj) for obj in avito_df.office]

new_qv = [ ]
for obj in avito_df.dirty_qv:
    if obj == []:
        new_qv.append(None)
    else:
        new_qv.append(re.sub('\D','',obj[0]))
        
avito_df['clean_qv'] = new_qv
print(avito_df.shape[0])
print(avito_df.clean_qv.isnull().sum())

25503
7219

In [32]:
avito_df[avito_df.freq =='вмесяц'].shape

(25444, 11)

In [33]:
avito_df = avito_df[avito_df.freq =='вмесяц']

In [115]:
avito_df[avito_df.clean_qv == '8500']

,href,Площадь11,Цена11,office,city,dirty_price,subject,freq,clean_price,dirty_qv,clean_qv,class
8416,/ivanovo/kommercheskaya_nedvizhimost/ofisy_kla...,Площадь: 35 м²; \nКласс здания: a,350 ₽ в месяц за м²,"Офисы класса ""А"", 35-8500 м², дц ""Мегаполис"" в...",Иваново,\n 12 250 р. в месяц \n\n,Ивановская обл.,вмесяц,12250.0,[8500 м²],8500,a

In [42]:
classes = [ ]
for item in avito_df['Площадь11']:
    jj = item.split('Класс здания:')
    if len(jj) > 1:
        classes.append(jj[-1][1])
    else:
        classes.append('')
avito_df['class'] = classes

preitog_table = avito_df[['class','city','clean_price','clean_qv']]

In [87]:
'Екатеринбург' in set(preitog_table.city)

True

In [160]:
ct_df = preitog_table[preitog_table.city == 'Самара']
#q_up = ct_df['clean_price'].quantile(1)
#q_down = ct_df['clean_price'].quantile(0)
#ct_df = ct_df[(ct_df['clean_price']<q_up) & (ct_df['clean_price']>q_down)]
print(ct_df.shape)
ct_df.head(2)

(707, 4)

   class    city  clean_price clean_qv
10     b  Самара       5000.0     None
30        Самара      85050.0      243

In [174]:
def pokaz(ct_df):
    s = 0
    n = 0
    mx = 0
    mp = 0
    sstr_pr = [ ]
    for item,jtem in zip(ct_df['clean_price'],ct_df['clean_qv']):
        try:
            n += 1
            if float(jtem) > mx:
                mx = float(jtem)
                mp = float(item)
            sstr_pr.append(float(item)/float(jtem))
        except:
            pass
    sstr_pr = np.array(sstr_pr)   
    sstr_pr = sstr_pr[(sstr_pr < float(pd.DataFrame(sstr_pr).quantile(0.9))) & (sstr_pr > float(pd.DataFrame(sstr_pr).quantile(0.01)))]
    md = np.median(sstr_pr)
    s = np.mean(sstr_pr)
    n = len(sstr_pr)
    #if len(sstr_pr) == 0:
    #    return 0,0,0,0
    return mx,md,s,n
    #return sstr_pr

def counter(city):
    ct_df = preitog_table[preitog_table.city == city]
    #q_up = ct_df['clean_price'].quantile(1)
    #q_down = ct_df['clean_price'].quantile(0)
    #ct_df = ct_df[(ct_df['clean_price']<q_up) & (ct_df['clean_price']>q_down)]
    #print(ct_df.shape)
    mx,med,s,n = pokaz(ct_df)
    
    mxa,meda,sa,na = pokaz(ct_df[ct_df['class'] == 'a'])
    mxb,medb,sb,nb = pokaz(ct_df[ct_df['class'] == 'b'])
    mxc,medc,sc,nc = pokaz(ct_df[ct_df['class'] == 'c'])
    mini_df = pd.DataFrame([city,n,mx,s,med,na,mxa,sa,meda,nb,mxb,sb,medb,nc,mxc,sc,medc]).T
    mini_df.columns = ['Город','Всего','Максима площ', 'Ср цена за год','Медианная цена за год',\
                                'Всего А','Максим площ А','Ср цена за год А','Медианная цена за год A',\
                                'Всего В','Максим площ В','Ср цена за год В','Медианная цена за год B',\
                                'Всего С','Максим площ C','Ср цена за год С','Медианная цена за год C']

    return(mini_df)

In [175]:
itog_cian_df = pd.DataFrame( )
for cty in int_city:
    itog_cian_df = itog_cian_df.append(counter(cty))

/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [176]:
itog_cian_df

,Город,Всего,Максима площ,Ср цена за год,Медианная цена за год,Всего А,Максим площ А,Ср цена за год А,Медианная цена за год A,Всего В,Максим площ В,Ср цена за год В,Медианная цена за год B,Всего С,Максим площ C,Ср цена за год С,Медианная цена за год C
0,Москва,4961,40000,9352.26,1746.64,631,15000,9114.15,2520.83,2607,40000,11497.5,1659.61,237,4800,2336.09,1126.42
0,Санкт-Петербург,2111,12000,2789.01,1000,207,8000,3648.4,1500,776,12000,3175.8,1092.62,152,3500,2531.62,800
0,Новосибирск,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Екатеринбург,300,4300,1940.53,673.298,25,800,1648.08,800,69,4300,1718.59,690.476,15,1000,1627.93,555.556
0,Нижний Новгород,302,2300,993.613,585,42,2000,591.464,600,37,1500,622.967,520,0,150,NaN,NaN
0,Казань,489,6439,1893.03,650,18,575,898.333,725,102,529,4252.38,1468.75,7,829,778.533,400
0,Челябинск,313,2000,688.271,460.526,26,700,2166.88,732.932,24,180,1061.29,500,7,25,1561.06,500
0,Омск,109,1800,471.647,450,7,360,716.691,573.333,12,151,816.832,621.429,0,1200,NaN,NaN
0,Самара,524,4843,1168.36,500,19,1652,784.872,650,56,1600,550.641,500,11,830,380.286,400
0,Ростов-на-Дону,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Уфа,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Красноярск,154,2500,981.267,510.315,11,1216,774.088,600,8,2500,1228.89,775,1,18,12693.6,12693.6
0,Пермь,395,4876,728.958,500,30,300,1502.65,578.917,27,2000,994.991,500,5,40,568.75,400
0,Воронеж,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Волгоград,177,3000,645.286,425,14,3000,443.739,464.286,25,1000,730.341,466.667,2,100,422.368,422.368
0,Краснодар,407,7000,886.248,595.745,79,4500,3649.57,712.857,53,545,723.756,600,13,441,668.666,500
0,Саратов,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Тюмень,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Тольятти,93,200,580.082,350,9,135,2459.2,735.294,4,190,287.25,208,0,15,NaN,NaN
0,Ижевск,156,2600,1262.23,549.932,13,2600,644.631,600,10,131,2984.71,650,0,188,NaN,NaN
0,Барнаул,106,2300,419.041,415.65,10,592,491.667,500,6,272,475.556,525,0,0,NaN,NaN
0,Ульяновск,104,2500,387.263,394.444,10,1200,490.761,495.192,0,0,NaN,NaN,0,10,NaN,NaN
0,Иркутск,145,3000,812.256,631.579,13,200,3383.78,900,7,500,1837.7,650,0,0,NaN,NaN
0,Хабаровск,80,1024,1134.88,844.952,10,750,1336.64,918.75,1,260,938.776,938.776,0,0,NaN,NaN
0,Ярославль,171,2524,662.425,533.333,20,515,706.991,701.852,13,1100,545.718,530,0,7,NaN,NaN
0,Владивосток,0,81,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Махачкала,13,660,409.895,407.407,0,0,NaN,NaN,0,660,NaN,NaN,0,0,NaN,NaN
0,Томск,88,1800,472.057,465.144,2,500,730,730,0,180,NaN,NaN,0,0,NaN,NaN
0,Оренбург,94,5000,562.266,412.476,14,5000,461.274,448.881,0,15,NaN,NaN,1,6,11450,11450
0,Кемерово,63,450,588.521,500,2,52,380.556,380.556,2,80,287.5,287.5,0,32,NaN,NaN
0,Новокузнецк,64,1236,521.052,513.158,2,130,619.231,619.231,1,110,545.455,545.455,0,20,NaN,NaN
0,Рязань,86,850,659.573,442.391,5,400,504.4,500,2,119,498.529,498.529,0,850,NaN,NaN
0,Астрахань,64,3600,408.55,400,5,1100,370,400,5,227,540,600,0,0,NaN,NaN
0,Набережные Челны,51,500,633.316,400,4,42,575.348,565.697,0,135,NaN,NaN,0,0,NaN,NaN
0,Пенза,70,862,700.393,476.804,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Липецк,84,823,612.727,447.222,2,67,6050,6050,15,150,1137.54,850,0,9,NaN,NaN
0,Киров,53,500,624.285,395,3,365,462.807,500,11,310,408.64,400,0,110,NaN,NaN
0,Чебоксары,53,500,610.425,417.391,4,113,382.5,345,4,218,908.75,462.5,0,0,NaN,NaN
0,Тула,99,1300,569.25,550,5,178,512.876,500,1,1300,545.455,545.455,0,87,NaN,NaN
0,Калининград,103,1000,859.035,528.302,14,700,650.926,639.785,8,270,583.18,553.947,2,306,425.98,425.98
0,Балашиха,27,860,2597.56,900.287,2,61,883.333,883.333,2,56,725,725,0,0,NaN,NaN
0,Курск,63,972,421.903,428.571,9,187,466.371,461.538,1,970,400,400,0,0,NaN,NaN
0,Ставрополь,77,826,401.441,350,11,826,518.947,400,1,230,300,300,0,506,NaN,NaN
0,Улан-Удэ,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN
0,Тверь,111,3000,1280.84,583.333,3,612,1500.63,571.895,2,2850,400,400,0,0,NaN,NaN
0,Магнитогорск,17,347,358.283,350,0,0,NaN,NaN,0,36,NaN,NaN,0,100,NaN,NaN
0,Сочи,53,850,661.39,666.667,7,100,753.159,772.727,2,113,1608.33,1608.33,0,0,NaN,NaN
0,Иваново,70,8500,513.213,412.5,10,8500,349.301,355.747,5,400,1042.92,500,0,400,NaN,NaN
0,Брянск,71,900,589.774,400,4,900,420.833,375,5,24,720.397,500,0,0,NaN,NaN

In [177]:
# pd.DataFrame.to_csv(itog_cian_df,'CIAN_clean_itog.csv')
writer = pd.ExcelWriter('output_avito.xlsx')
itog_cian_df.to_excel(writer,'Sheet1')
writer.save()

In [43]:
int_city = ['Москва',
'Санкт-Петербург',
'Новосибирск',
'Екатеринбург',
'Нижний Новгород',
'Казань',
'Челябинск',
'Омск',
'Самара',
'Ростов-на-Дону',
'Уфа',
'Красноярск',
'Пермь',
'Воронеж',
'Волгоград',
'Краснодар',
'Саратов',
'Тюмень',
'Тольятти',
'Ижевск',
'Барнаул',
'Ульяновск',
'Иркутск',
'Хабаровск',
'Ярославль',
'Владивосток',
'Махачкала',
'Томск',
'Оренбург',
'Кемерово',
'Новокузнецк',
'Рязань',
'Астрахань',
'Набережные Челны',
'Пенза',
'Липецк',
'Киров',
'Чебоксары',
'Тула',
'Калининград',
'Балашиха',
'Курск',
'Ставрополь',
'Улан-Удэ',
'Тверь',
'Магнитогорск',
'Сочи',
'Иваново',
'Брянск']